name: Compile Scripts

on: 
  push:
    branches: [ main ]
  workflow_dispatch:  # Разрешает ручной запуск

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install AutoHotkey
      run: choco install autohotkey -y
      
    - name: Compile scripts
      run: |
        "C:\ProgramData\chocolatey\bin\Ahk2Exe.exe" /in "Browsers/Chrome_PlayPause.ahk" /out "Chrome_PlayPause.exe"
        "C:\ProgramData\chocolatey\bin\Ahk2Exe.exe" /in "Browsers/Firefox_PlayPause.ahk" /out "Firefox_PlayPause.exe"
        # Добавьте другие браузеры
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Binaries
        path: "*.exe"
